# Generated by Django 4.1.3 on 2022-11-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='name',
        ),
    ]
