# Generated by Django 4.1.3 on 2022-11-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0002_rename_type_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='available',
            field=models.BooleanField(default='True'),
        ),
    ]
