# Generated by Django 4.1.3 on 2022-11-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0004_alter_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo',
            new_name='mainPhoto',
        ),
        migrations.AddField(
            model_name='listing',
            name='otherPhotos',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
