# Generated by Django 4.1.3 on 2022-11-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0005_rename_photo_listing_mainphoto_listing_otherphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='otherPhotos',
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='adirondack_upcycled_app.listing')),
            ],
        ),
    ]
