# Generated by Django 4.1.3 on 2022-11-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0007_remove_listing_price_listing_photo1_listing_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9999.99, max_digits=7),
        ),
    ]
