# Generated by Django 4.1.3 on 2022-11-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0009_alter_listing_photo1_alter_listing_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hrefName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
