# Generated by Django 4.1.3 on 2022-12-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0010_category_hrefname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField()),
                ('description', models.TextField()),
                ('archive', models.BooleanField(default='False')),
            ],
        ),
    ]
