# Generated by Django 4.1.3 on 2022-12-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0011_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
