# Generated by Django 4.1.3 on 2023-01-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0012_alter_event_archive_alter_listing_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=2),
        ),
    ]
