# Generated by Django 4.1.3 on 2023-01-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0013_listing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
