# Generated by Django 4.1.6 on 2023-02-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adirondack_upcycled_app', '0016_alter_listing_mainphoto_alter_listing_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='mainPhoto',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
